// <auto-generated>
// Suppress design warnings for test assembly where public visibility is required by MSTest.
// </auto-generated>
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1515:Consider making types internal", Justification = "MSTest requires public test classes and methods for discovery.")]
