<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <!-- Only supports x64 due to the RocksDB dependency -->
    <Platform>x64</Platform>
    <Platforms>$(Platform)</Platforms>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Microsoft.MSBuildCache.AzurePipelines.Tests</RootNamespace>
    <!-- MSTest requires public test classes even though the test host is an application. -->
    <NoWarn>$(NoWarn);CA1515</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AzurePipelines\Microsoft.MSBuildCache.AzurePipelines.csproj" />
  </ItemGroup>
</Project>
